//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HousingManagement
{
    using System;
    using System.Collections.Generic;
    
    public partial class Invoices
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Invoices()
        {
            this.ResidentServices = new HashSet<ResidentServices>();
        }
    
        public int Id { get; set; }
        public Nullable<int> ResidentId { get; set; }
        public Nullable<int> ServiceId { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public Nullable<System.DateTime> InvoiceDate { get; set; }
        public Nullable<bool> IsPaid { get; set; }
    
        public virtual Residents Residents { get; set; }
        public virtual Services Services { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ResidentServices> ResidentServices { get; set; }
    }
}
