//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HousingManagement
{
    using System;
    using System.Collections.Generic;
    
    public partial class Payments
    {
        public int Id { get; set; }
        public Nullable<int> ResidentId { get; set; }
        public Nullable<int> ServiceId { get; set; }
        public Nullable<decimal> Volume { get; set; }
        public Nullable<System.DateTime> PaymentDate { get; set; }
    
        public virtual Residents Residents { get; set; }
        public virtual Services Services { get; set; }
    }
}
